# Generated by Django 5.2.17 on 2026-09-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('external_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(max_length=48)),
                ('format', models.CharField(max_length=32)),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=7)),
                ('mandatory', models.BooleanField(default=False)),
                ('target_roles', models.JSONField(default=list)),
                ('target_grades', models.JSONField(default=list)),
                ('develops_skills', models.JSONField(default=list)),
                ('prerequisites', models.JSONField(default=dict)),
                ('upcoming_sessions', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['external_id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('external_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('type', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=96)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('external_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=160)),
                ('department', models.CharField(max_length=160)),
                ('role', models.CharField(max_length=120)),
                ('grade', models.CharField(max_length=32)),
                ('hire_date', models.DateField()),
                ('tenure_months', models.PositiveIntegerField(default=0)),
                ('work_format', models.CharField(max_length=32)),
                ('preferred_language', models.CharField(default='ru', max_length=8)),
                ('career_goal', models.JSONField(blank=True, null=True)),
                ('skills', models.JSONField(default=dict)),
                ('last_review_date', models.DateField()),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='career.employee')),
            ],
            options={
                'ordering': ['full_name', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='RoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
                ('grade', models.CharField(max_length=32)),
                ('required_skills', models.JSONField(default=dict)),
                ('critical_skills', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['role', 'grade'],
                'constraints': [models.UniqueConstraint(fields=('role', 'grade'), name='unique_role_grade')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='career.employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_quests', to='career.learningevent')),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'event'), name='unique_employee_quest')],
            },
        ),
        migrations.CreateModel(
            name='ActivityHistory',
            fields=[
                ('record_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=32)),
                ('completion_pct', models.PositiveSmallIntegerField(default=0)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assigned_by', models.CharField(max_length=32)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='career.employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='career.learningevent')),
            ],
            options={
                'ordering': ['date', 'record_id'],
                'indexes': [models.Index(fields=['employee', 'status'], name='career_acti_employe_5e43c8_idx'), models.Index(fields=['event', 'status'], name='career_acti_event_i_a7fdb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to='career.employee')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_transactions', to='career.learningevent')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'event', 'reason'), name='unique_employee_event_xp_reason')],
            },
        ),
    ]
