# Generated by Django 5.2.17 on 2026-09-23 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=120)),
                ('grade', models.CharField(max_length=40)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('last_review_date', models.DateField()),
                ('baseline_skills', models.JSONField(default=dict)),
                ('career_goal', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_hours', models.FloatField(default=0)),
                ('format', models.CharField(blank=True, max_length=40)),
                ('mandatory', models.BooleanField(default=False)),
                ('repeatable', models.BooleanField(default=False)),
                ('target_roles', models.JSONField(default=list)),
                ('target_grades', models.JSONField(default=list)),
                ('develops_skills', models.JSONField(default=list)),
                ('prerequisites', models.JSONField(default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='core.employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.learningevent')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=60, unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('completion_pct', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.learningevent')),
            ],
            options={
                'ordering': ['date', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='RoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
                ('grade', models.CharField(max_length=40)),
                ('required_skills', models.JSONField(default=dict)),
                ('critical_skills', models.JSONField(default=list)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role', 'grade'), name='unique_role_grade')],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to='core.employee')),
                ('quest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.employeequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='employeequest',
            constraint=models.UniqueConstraint(fields=('employee', 'event'), name='unique_employee_event_quest'),
        ),
    ]
